# Generated by Django 2.1.3 on 2018-11-30 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181130_1459'),
        ('quiz', '0002_auto_20181125_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('correct', models.BooleanField(default=False, help_text='Is this a correct answer?')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='question',
        ),
        migrations.RemoveField(
            model_name='studentresponse',
            name='student',
        ),
        migrations.RemoveField(
            model_name='question',
            name='a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='b',
        ),
        migrations.RemoveField(
            model_name='question',
            name='c',
        ),
        migrations.RemoveField(
            model_name='question',
            name='d',
        ),
        migrations.RemoveField(
            model_name='question',
            name='solution',
        ),
        migrations.AlterField(
            model_name='quizresponse',
            name='responses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.QuestionResponse'),
        ),
        migrations.DeleteModel(
            name='StudentResponse',
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Question'),
        ),
    ]
