# Generated by Django 2.1.3 on 2018-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181125_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(choices=[('3', '3'), ('2', '2'), ('4', '4'), ('1', '1')], default='1', max_length=10),
        ),
    ]
