# Generated by Django 2.1.3 on 2018-11-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181130_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(choices=[('1', '1'), ('3', '3'), ('4', '4'), ('2', '2')], default='1', max_length=10),
        ),
    ]
