# Generated by Django 2.1.3 on 2018-11-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181130_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
    ]
