# Generated by Django 2.1.3 on 2018-12-15 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181130_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(choices=[('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], default='1', max_length=10),
        ),
    ]
