# Generated by Django 2.1.4 on 2018-12-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20181215_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(choices=[('4', '4'), ('2', '2'), ('3', '3'), ('1', '1')], default='1', max_length=10),
        ),
    ]
